FROM amazon/aws-sam-cli-build-image-ruby2.7

# Lamby user to mirror host machine user:group.
ARG HOST_UID
ARG HOST_GID
RUN mkdir /lamby \
    && /usr/sbin/groupadd --gid $HOST_GID --system --force lamby \
    && /usr/sbin/useradd --uid $HOST_UID --gid $HOST_GID --non-unique --home-dir /lamby --shell /bin/bash --system lamby \
    && chown $HOST_UID:$HOST_GID /lamby

# Ensure minimum required SAM version.
ENV SAM_CLI_VERSION=1.23.0
RUN curl -L "https://github.com/aws/aws-sam-cli/releases/download/v${SAM_CLI_VERSION}/aws-sam-cli-linux-x86_64.zip" \
         -o "aws-sam-cli-linux-x86_64.zip" && \
    unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation && \
    ./sam-installation/install && \
    rm -rf ./sam-installation ./aws-sam-cli-linux-x86_64.zip

# Node for JavaScript.
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash - && \
    yum install -y nodejs && \
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg && \
    yum install -y yarn

WORKDIR /var/task
